### ISSUE TITLE
[Model Certification] - Eco-dim07 Basic Zigbee

### ISSUE THREAD

**Issue by gniersma** [zigbeefordomoticz/z4d-certified-devices#21]
Hi, 

1. Please do provide device information such as Brand and Model name.
https://www.ecodim.nl/nl/eco-dim07-zigbee-basic.html

Bought one eco-dim to test with. This did work, So I ordered 6 additional dimmers.
Unfortunatly I don't get it working.
the additional dimmers do show up in the list "apparaten" after pairing but, are not optimized or recognised 

I enclose: error log + export which show the good working dimmer
[export (2).json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13260531/export.2.json)
[errors.json](https://github.com/zigbeefordomoticz/z4d-certified-devices/files/13260532/errors.json)

Hope someone knows a solution for my problem

Thx Gerard

2023-11-05 15:18:28,451 INFO    :b'Zigbee for Domoticz (z4d) plugin stable7-7.1.004 started'
2023-11-05 15:18:28,485 INFO    :b'Plugin Database: DeviceList-14.txt'
2023-11-05 15:18:28,486 INFO    :b'Pathname to z4d_certified_devices /usr/local/lib/python3.9/dist-packages/z4d_certified_devices/'
2023-11-05 15:18:28,486 INFO    :b'Loading ZCL Cluster definitions'
2023-11-05 15:18:28,491 INFO    :b' - ZCL Cluster 0000 - (V1) Basic loaded'
2023-11-05 15:18:28,494 INFO    :b' - ZCL Cluster 0001 - (V1) Power loaded'
2023-11-05 15:18:28,496 INFO    :b' - ZCL Cluster 0002 - (V1) Device Temperature Configuration loaded'
2023-11-05 15:18:28,498 INFO    :b' - ZCL Cluster 0003 - (V1) Identify loaded'
2023-11-05 15:18:28,500 INFO    :b' - ZCL Cluster 0004 - (V1) Groups loaded'
2023-11-05 15:18:28,502 INFO    :b' - ZCL Cluster 0005 - (V1) Scenes loaded'
2023-11-05 15:18:28,505 INFO    :b' - ZCL Cluster 0006 - (V1) On/Off loaded'
2023-11-05 15:18:28,507 INFO    :b' - ZCL Cluster 0007 - (V1) On/Off Switch Configuration loaded'
2023-11-05 15:18:28,509 INFO    :b' - ZCL Cluster 0008 - (V1) Level loaded'
2023-11-05 15:18:28,511 INFO    :b' - ZCL Cluster 0009 - (V1) Alarms loaded'
2023-11-05 15:18:28,514 INFO    :b' - ZCL Cluster 000a - (V1) Time loaded'
2023-11-05 15:18:28,516 INFO    :b' - ZCL Cluster 000d - (V1) Analog Output loaded'
2023-11-05 15:18:28,518 INFO    :b' - ZCL Cluster 000f - (V1) Binary Input loaded'
2023-11-05 15:18:28,521 INFO    :b' - ZCL Cluster 0013 - (V1) Multistate Output loaded'
2023-11-05 15:18:28,523 INFO    :b' - ZCL Cluster 0019 - (V1) OTA Upgrade loaded'
2023-11-05 15:18:28,526 INFO    :b' - ZCL Cluster 0020 - (V1) Poll Control loaded'
2023-11-05 15:18:28,528 INFO    :b' - ZCL Cluster 0102 - (V1) Window Covering loaded'
2023-11-05 15:18:28,531 INFO    :b' - ZCL Cluster 0202 - (V1) Fan Control loaded'
2023-11-05 15:18:28,533 INFO    :b' - ZCL Cluster 0204 - (V1) Thermostat User Interface Configuration loaded'
2023-11-05 15:18:28,538 INFO    :b' - ZCL Cluster 0300 - (V1) Color Control loaded'
2023-11-05 15:18:28,540 INFO    :b' - ZCL Cluster 0301 - (V1) Ballast Configuration loaded'
2023-11-05 15:18:28,543 INFO    :b' - ZCL Cluster 0400 - (V1) Illuminance Level Sensing loaded'
2023-11-05 15:18:28,545 INFO    :b' - ZCL Cluster 0402 - (V1) Temperature Measurement loaded'
2023-11-05 15:18:28,548 INFO    :b' - ZCL Cluster 0403 - (V1) Pressure Measurement loaded'
2023-11-05 15:18:28,550 INFO    :b' - ZCL Cluster 0405 - (V1) Relative Humidity Measurement loaded'
2023-11-05 15:18:28,563 INFO    :b' - ZCL Cluster 0406 - (V1) Occupancy Sensing loaded'
2023-11-05 15:18:28,568 INFO    :b' - ZCL Cluster 0700 - (V1) Price loaded'
2023-11-05 15:18:28,572 INFO    :b' - ZCL Cluster 0702 - (V1) Metering (Smart Energy) loaded'
2023-11-05 15:18:28,575 INFO    :b' - ZCL Cluster 0b01 - (V1) Meter Identification loaded'
2023-11-05 15:18:28,578 INFO    :b' - ZCL Cluster 0b04 - (V1) Electrical Measurement loaded'
2023-11-05 15:18:28,581 INFO    :b' - ZCL Cluster 0b05 - (V1) Diagnostics loaded'
2023-11-05 15:18:28,583 INFO    :b' - ZCL Cluster e000 - (V1) Tuya E000 Private Cluster loaded'
2023-11-05 15:18:28,585 INFO    :b' - ZCL Cluster e001 - (V1) Tuya E001 Private Cluster loaded'
2023-11-05 15:18:28,587 INFO    :b' - ZCL Cluster e002 - (V1) Tuya E002 Private Cluster loaded'
2023-11-05 15:18:28,589 INFO    :b' - ZCL Cluster fcc0 - (V1) LUMI Private Cluster loaded'
2023-11-05 15:18:28,592 INFO    :b' - ZCL Cluster ff66 - (V1) Lixee Zlinky private cluster loaded'
2023-11-05 15:18:28,597 INFO    :b'DeviceConf loaded - 16 confs loaded'
2023-11-05 15:18:28,608 INFO    :b'Local-Device conf loaded - 21 confs loaded'
2023-11-05 15:18:29,391 INFO    :b'Certified Devices loaded - 522 confs loaded'
2023-11-05 15:18:29,392 INFO    :b'load ListOfDevice'
2023-11-05 15:18:29,413 ERROR   : [       MainThread] Not Loading 0ba8 as Status: UNKNOW
2023-11-05 15:18:29,417 ERROR   : [       MainThread] Not Loading a7ec as Status: UNKNOW
2023-11-05 15:18:29,421 INFO    :b'2 Entries loaded from /home/pi/domoticz/plugins/Domoticz-Zigbee/Data/DeviceList-14.txt'
2023-11-05 15:18:29,427 INFO    :b'Transport mode: ZigpyEZSP'
2023-11-05 15:18:30,738 INFO    :b'Start Zigpy Transport on EZSP'
2023-11-05 15:18:30,738 DEBUG   :Using selector: EpollSelector
2023-11-05 15:18:30,742 INFO    :b'ZigpyTransport: thread_processing_and_sending Thread start.'
2023-11-05 15:18:30,743 INFO    :b'Start Web Server connection'
2023-11-05 15:18:30,775 INFO    :b'Web backend for Web User Interface started on port: 9440'
2023-11-05 15:18:31,019 INFO    :b'Plugin looks to upgrade the Certified Device package'
2023-11-05 15:18:31,457 INFO    :b'Started radio ezsp port: /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220817103732-if00'
2023-11-05 15:18:31,459 DEBUG   :Using selector: EpollSelector
2023-11-05 15:18:32,835 INFO    :b'Bellows Radio register default Ep'
2023-11-05 15:18:33,405 INFO    :b"EZSP Configuration {'device': {'path': '/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220817103732-if00', 'baudrate': 115200, 'flow_control': 'software'}, 'network': {'channel': 20, 'tc_address': None, 'tc_link_key': 5a:69:67:42:65:65:41:6c:6c:69:61:6e:63:65:30:39, 'extended_pan_id': None, 'key': None, 'update_id': 0, 'channels': <Channels.CHANNEL_25|CHANNEL_20|CHANNEL_15|CHANNEL_11: 34637824>, 'pan_id': None, 'key_sequence_number': 0}, 'ezsp_config': {}, 'topology_scan_enabled': False, 'handle_unknown_devices': True, 'source_routing': False, 'backup_enabled': True, 'backup_period': 1, 'topology_scan_skip_coordinator': False, 'validate_network_settings': False, 'database_path': None, 'additional_endpoints': [], 'max_watchdog_failures': 4, 'startup_energy_scan': True, 'max_concurrent_requests': 8, 'ota': {'ledvance_provider': False, 'otau_directory': None, 'sonoff_provider': False, 'thirdreality_provider': False, 'salus_provider': False, 'ikea_provider': False, 'inovelli_provider': False}, 'use_thread': True, 'ezsp_policies': {}, 'topology_scan_period': 240}"
2023-11-05 15:18:33,407 INFO    :b'Number of devices recently active in Coordinator = 0'
2023-11-05 15:18:33,443 INFO    :b'EZSP Radio manufacturer: '
2023-11-05 15:18:33,444 INFO    :b'EZSP Radio board name: '
2023-11-05 15:18:33,447 INFO    :b'EmberZNet version: 6.10.3.0 build 297'
2023-11-05 15:18:33,450 INFO    :b'bellows_extract_versioning_for_plugin Manuf:  Name:  Version: 6.10.3.0 build 297'
2023-11-05 15:18:33,451 INFO    :b'Network settings'
2023-11-05 15:18:33,453 INFO    :b'  Device IEEE: e0:79:8d:ff:fe:71:87:dd'
2023-11-05 15:18:33,454 INFO    :b'  Device NWK: 0x0000'
2023-11-05 15:18:33,456 INFO    :b'  Network Update Id: 0x0000'
2023-11-05 15:18:33,457 INFO    :b'  PAN ID: 0xDB14'
2023-11-05 15:18:33,458 INFO    :b'  Extended PAN ID: e9:b6:ec:21:3f:b0:40:91'
2023-11-05 15:18:33,459 INFO    :b'  Channel: 20'
2023-11-05 15:18:33,461 INFO    :b'Decode8010 980610306.10.3.0 build 297'
2023-11-05 15:18:33,462 INFO    :b'Decode8010 Major: 98 Minor: 1030 Full: 6.10.3.0 build 297'
2023-11-05 15:18:33,463 INFO    :b'Untested Zigbee adaptater model. If this is a Sonoff USB Dongle E that is known issue, otherwise please report to the Zigbee for Domoticz team'
2023-11-05 15:18:33,464 INFO    :b'Installer Version Number: 6.10.3.0 build 297'
2023-11-05 15:18:33,464 INFO    :b'Branch Version: ==> Unknown Silicon Labs <=='
2023-11-05 15:18:33,466 INFO    :b'Zigbee Coordinator ieee: e0798dfffe7187dd , short addr: 0000'
2023-11-05 15:18:33,466 INFO    :b'Network state UP, PANID: db14 extPANID: 0xe9b6ec213fb04091 Channel: 20'
2023-11-05 15:20:38,412 INFO    :b'Certified Device package upgrade results'
2023-11-05 15:20:38,413 INFO    :b'Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple'
2023-11-05 15:20:38,413 INFO    :b'Requirement already satisfied: z4d-certified-devices in /usr/local/lib/python3.9/dist-packages (2.137)'
2023-11-05 15:20:38,413 INFO    :b'Collecting z4d-certified-devices'
2023-11-05 15:20:38,413 INFO    :b'  Using cached https://www.piwheels.org/simple/z4d-certified-devices/z4d_certified_devices-2.137-py3-none-any.whl (344 kB)'
2023-11-05 15:20:38,413 INFO    :b'  Downloading https://www.piwheels.org/simple/z4d-certified-devices/z4d_certified_devices-2.136-py3-none-any.whl (342 kB)'
2023-11-05 15:20:38,414 INFO    :b''
2023-11-05 15:20:38,414 INFO    :b'Domoticz Widgets usage is at 1.6 % (251 units free)'
2023-11-05 15:20:47,079 INFO    :b'Request Disabling Accepting new Hardware'
2023-11-05 15:20:47,101 INFO    :b"PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 0, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1699194047.0780988, 'ACKIsDisable': False, 'Sqn': None}"
2023-11-05 15:20:47,102 INFO    :b'PERMIT-TO-JOIN: duration: 0 for Radio: ezsp for node: None'
2023-11-05 15:20:47,102 INFO    :b'Calling self.app.permit(time_s=0, node=None )'
2023-11-05 15:20:47,131 INFO    :b'returning from the self.app.permit(time_s=0, node=None )'
2023-11-05 15:20:52,094 INFO    :b'Switch Blue Led On'
2023-11-05 15:20:52,097 INFO    :b'coordinator set to Certification : 1/CE -> CE'
2023-11-05 15:20:52,936 INFO    :b'ota_scan_folder Following Firmware have been loaded '
2023-11-05 15:20:52,937 INFO    :b'Plugin with Zigpy, Coordinator Unknown Silicon Labs firmware UNK - 6.10.3.0 build 297 correctly initialized'
2023-11-05 15:21:14,757 INFO    :b'We have detected a potential new firmware for the device None [acea]'
2023-11-05 15:21:14,758 INFO    :b'   current version: 2'
2023-11-05 15:21:14,759 INFO    :b'     firmware type: 1000'
2023-11-05 15:21:14,759 INFO    :b'    newest version: 4'
2023-11-05 15:21:14,760 INFO    :b'     firmware type: 1000'
2023-11-05 15:21:14,761 INFO    :b'   URL to download: https://github.com/Koenkk/zigbee-OTA/raw/master/images/EcoDim/ZB21S3_HZC_Dimmer1_EcoDim-Zigbee%203.0_1.01_20230908.ota'
2023-11-05 15:21:14,761 INFO    :b'   to get this Manufacturer supported: 4714'
2023-11-05 15:21:14,762 INFO    :b"   provide those informations: {'fileVersion': 4, 'fileSize': 286646, 'manufacturerCode': 4714, 'imageType': 1000, 'sha512': '9b7835e32ef5af35385710332838099c5dce99a398ae04a1a769d67935fb0752ca4da58892f13bc842cbf8f9ae20516142fe9b66eff3e8ebef6577a71a1d9b0b', 'url': 'https://github.com/Koenkk/zigbee-OTA/raw/master/images/EcoDim/ZB21S3_HZC_Dimmer1_EcoDim-Zigbee%203.0_1.01_20230908.ota', 'path': 'images/EcoDim/ZB21S3_HZC_Dimmer1_EcoDim-Zigbee 3.0_1.01_20230908.ota'}"
2023-11-05 15:21:14,763 INFO    :b'   open an Issue on GitHub here: https://github.com/zigbeefordomoticz/Domoticz-Zigbee/issues/new?assignees=&labels=&template=feature_request.md&title='
2023-11-05 15:29:39,429 WARNING :Received relays from an unknown device: 0xa7ec
2023-11-05 15:29:39,484 WARNING :Unknown device AddrModeAddress(addr_mode=<AddrMode.NWK: 2>, address=0xA7EC)
2023-11-05 15:29:39,491 WARNING :Received relays from an unknown device: 0xa7ec
2023-11-05 15:29:40,550 ERROR   : [ZigpyForwarder_14] Decode 8041 - Receive an IEEE: 84b4dbfffe0bca7a with a NwkId: a7ec, seems not known by the plugin
2023-11-05 15:29:41,557 ERROR   : [ZigpyForwarder_14] Decode 8041 - Receive an IEEE: 84b4dbfffe0bca7a with a NwkId: a7ec, seems not known by the plugin
2023-11-05 15:29:42,562 ERROR   : [ZigpyForwarder_14] Decode 8041 - Receive an IEEE: 84b4dbfffe0bca7a with a NwkId: a7ec, seems not known by the plugin
2023-11-05 15:29:42,567 INFO    :b'decode8002_and_process unknown NwkId: a7ec for ZCL frame 0180020032ff0001040019010102a7ec020000010a01006a12e80302000000a803'
2023-11-05 15:29:45,468 INFO    :b'decode8002_and_process unknown NwkId: a7ec for ZCL frame 0180020032ff0001040019010102a7ec020000010b01006a12e80302000000a403'
2023-11-05 15:29:48,454 INFO    :b'decode8002_and_process unknown NwkId: a7ec for ZCL frame 0180020032ff0001040019010102a7ec020000010c01006a12e80302000000a803'
2023-11-05 15:29:51,444 INFO    :b'decode8002_and_process unknown NwkId: a7ec for ZCL frame 0180020032ff0001040019010102a7ec020000010d01006a12e80302000000a403'
2023-11-05 15:31:22,134 INFO    :b'Request Accepting new Hardware for 240 seconds '
2023-11-05 15:31:22,206 INFO    :b"PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 240, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1699194682.1317196, 'ACKIsDisable': False, 'Sqn': None}"
2023-11-05 15:31:22,209 INFO    :b'PERMIT-TO-JOIN: duration: 240 for Radio: ezsp for node: None'
2023-11-05 15:31:22,210 INFO    :b'Calling self.app.permit(time_s=240, node=None )'
2023-11-05 15:31:22,243 INFO    :b'returning from the self.app.permit(time_s=240, node=None )'
2023-11-05 15:31:24,192 INFO    :b'Request Accepting new Hardware for 240 seconds '
2023-11-05 15:31:24,259 INFO    :b"PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 240, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1699194684.1896338, 'ACKIsDisable': False, 'Sqn': None}"
2023-11-05 15:31:24,260 INFO    :b'PERMIT-TO-JOIN: duration: 240 for Radio: ezsp for node: None'
2023-11-05 15:31:24,263 INFO    :b'Calling self.app.permit(time_s=240, node=None )'
2023-11-05 15:31:24,294 INFO    :b'returning from the self.app.permit(time_s=240, node=None )'
2023-11-05 15:31:51,082 INFO    :b'--> Adding device a7ec in self.DevicesInPairingMode'
2023-11-05 15:31:51,082 INFO    :b"--> ['a7ec']"
2023-11-05 15:31:51,083 INFO    :b'[None] NEW OBJECT: a7ec None'
2023-11-05 15:31:53,086 INFO    :b'--> Adding device 0ba8 in self.DevicesInPairingMode'
2023-11-05 15:31:53,087 INFO    :b"--> ['a7ec', '0ba8']"
2023-11-05 15:31:53,087 INFO    :b'[None] NEW OBJECT: 0ba8 None'
2023-11-05 15:31:54,087 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:31:54,095 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:31:58,107 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:31:58,117 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:31:59,111 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:31:59,118 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:04,125 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:04,143 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:06,127 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:06,134 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:08,132 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:08,141 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:10,141 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:10,151 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:12,145 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:12,150 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:15,151 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:15,157 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:16,157 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:16,175 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:18,159 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:18,166 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:20,165 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:20,171 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:22,064 ERROR   : [       MainThread] [6] NEW OBJECT: a7ec Not able to get all needed attributes on time
2023-11-05 15:32:22,074 ERROR   : [       MainThread] processNotinDB - not able to find response from a7ec stop process at 0045
2023-11-05 15:32:22,087 ERROR   : [       MainThread] processNotinDB - Collected Infos are : {'Version': '3', 'ZDeviceName': '', 'Status': 'UNKNOW', 'SQN': '', 'Ep': {}, 'Heartbeat': '1', 'RIA': '6', 'LQI': {}, 'Battery': {}, 'Model': '', 'ForceAckCommands': [], 'MacCapa': '8e', 'IEEE': '84b4dbfffe0bca7a', 'Type': {}, 'ProfileID': {}, 'ZDeviceID': {}, 'App Version': '', 'Attributes List': {}, 'DeviceType': 'FFD', 'HW Version': '', 'Last Cmds': [], 'LogicalType': 'Router', 'Manufacturer': '', 'Manufacturer Name': '', 'NbEp': '', 'PowerSource': 'Main', 'ReadAttributes': {}, 'ReceiveOnIdle': '', 'Stack Version': '', 'Stamp': {'time': 1699194738.164849, 'Time': '2023-11-05 15:32:18', 'MsgType': '  4d', 'LastSeen': 1699194738}, 'ZCL Version': '', 'Health': 'Live', 'Capability': ['Full-Function Device', 'Main Powered', 'Receiver during Idle', 'Standard security', 'NwkAddr should be allocated'], 'ZDPSQN': '05', 'PairingInProgress': True, 'ConsistencyCheck': 'Bad Pairing'}
2023-11-05 15:32:22,170 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:22,176 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:25,178 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:25,178 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:27,056 ERROR   : [       MainThread] [6] NEW OBJECT: 0ba8 Not able to get all needed attributes on time
2023-11-05 15:32:27,061 ERROR   : [       MainThread] processNotinDB - not able to find response from 0ba8 stop process at 0045
2023-11-05 15:32:27,067 ERROR   : [       MainThread] processNotinDB - Collected Infos are : {'Version': '3', 'ZDeviceName': '', 'Status': 'UNKNOW', 'SQN': '', 'Ep': {}, 'Heartbeat': '2', 'RIA': '6', 'LQI': {}, 'Battery': {}, 'Model': '', 'ForceAckCommands': [], 'MacCapa': '8e', 'IEEE': '84b4dbfffe0bcb6d', 'Type': {}, 'ProfileID': {}, 'ZDeviceID': {}, 'App Version': '', 'Attributes List': {}, 'DeviceType': 'FFD', 'HW Version': '', 'Last Cmds': [], 'LogicalType': 'Router', 'Manufacturer': '', 'Manufacturer Name': '', 'NbEp': '', 'PowerSource': 'Main', 'ReadAttributes': {}, 'ReceiveOnIdle': '', 'Stack Version': '', 'Stamp': {'time': 1699194740.1696424, 'Time': '2023-11-05 15:32:20', 'MsgType': '  4d', 'LastSeen': 1699194740}, 'ZCL Version': '', 'Health': 'Live', 'Capability': ['Full-Function Device', 'Main Powered', 'Receiver during Idle', 'Standard security', 'NwkAddr should be allocated'], 'ZDPSQN': '05', 'PairingInProgress': True, 'ConsistencyCheck': 'Bad Pairing'}
2023-11-05 15:32:28,186 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:28,198 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:29,189 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:29,195 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:33,201 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:33,218 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:34,200 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:34,207 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:35,205 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:35,205 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:36,206 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:36,214 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:38,212 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:38,213 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:40,217 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:40,222 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:42,223 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:42,229 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:43,226 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:43,232 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:32:49,247 INFO    :b'Device Annoucement: NwkId: acea Ieee: 84b4dbfffe0bc8f9 MacCap: 8e'
2023-11-05 15:32:49,264 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device acea'
2023-11-05 15:32:50,251 INFO    :b'Device Annoucement: NwkId: a7ec Ieee: 84b4dbfffe0bca7a MacCap: 8e'
2023-11-05 15:32:50,262 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device a7ec'
2023-11-05 15:32:51,256 INFO    :b'Device Annoucement: NwkId: 0ba8 Ieee: 84b4dbfffe0bcb6d MacCap: 8e'
2023-11-05 15:32:51,271 INFO    :b'Forcing a check of configure reporting after Device Annoucement on Main Powered device 0ba8'
2023-11-05 15:33:12,357 INFO    :b'Decode0042 - acea/00 requested manuf code -responding with Manufacturer: 0000'
2023-11-05 15:33:12,358 ERROR   :Task exception was never retrieved
future: <Task finished name='cleanup_tc_link_key' coro=<ControllerApplication.cleanup_tc_link_key() done, defined at /usr/local/lib/python3.9/dist-packages/bellows/zigbee/application.py:115> exception=TimeoutError()>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bellows/ezsp/protocol.py", line 148, in command
    return await future
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/bellows/zigbee/application.py", line 117, in cleanup_tc_link_key
    (index,) = await self._ezsp.findKeyTableEntry(ieee, True)
  File "/usr/local/lib/python3.9/dist-packages/bellows/ezsp/protocol.py", line 148, in command
    return await future
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/dist-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2023-11-05 15:33:12,359 INFO    :b'Decode0042 - a7ec/00 requested manuf code -responding with Manufacturer: 0000'
2023-11-05 15:33:12,436 INFO    :b'Decode8046 - Match Descriptor response: SQN: 00 Status: 00 Nwkid: 0ba8 Lenght: 00 List: '
2023-11-05 15:33:12,461 INFO    :b'Decode8046 - Match Descriptor response: SQN: 00 Status: 00 Nwkid: a7ec Lenght: 00 List: '
2023-11-05 15:33:12,873 ERROR   : [ZigpyForwarder_14] Decode8045 - KeyError: MsgDataShAddr = 0ba8
2023-11-05 15:33:12,954 ERROR   : [ZigpyForwarder_14] Decode8045 - KeyError: MsgDataShAddr = a7ec
2023-11-05 15:35:22,198 INFO    :b'Request Disabling Accepting new Hardware'
2023-11-05 15:35:22,212 INFO    :b"PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 0, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1699194922.197252, 'ACKIsDisable': False, 'Sqn': None}"
2023-11-05 15:35:22,212 INFO    :b'PERMIT-TO-JOIN: duration: 0 for Radio: ezsp for node: None'
2023-11-05 15:35:22,214 INFO    :b'Calling self.app.permit(time_s=0, node=None )'
2023-11-05 15:35:22,242 INFO    :b'returning from the self.app.permit(time_s=0, node=None )'
2023-11-05 15:35:31,877 INFO    :b'Request Disabling Accepting new Hardware'
2023-11-05 15:35:31,899 INFO    :b"PERMIT-TO-JOIN: {'cmd': 'PERMIT-TO-JOIN', 'datas': {'Duration': 0, 'targetRouter': 'FFFC'}, 'NwkId': None, 'TimeStamp': 1699194931.876008, 'ACKIsDisable': False, 'Sqn': None}"
2023-11-05 15:35:31,900 INFO    :b'PERMIT-TO-JOIN: duration: 0 for Radio: ezsp for node: None'
2023-11-05 15:35:31,901 INFO    :b'Calling self.app.permit(time_s=0, node=None )'
2023-11-05 15:35:31,928 INFO    :b'returning from the self.app.permit(time_s=0, node=None )'
2023-11-05 15:40:55,147 INFO    :b'lookupForIEEE found a matching IEEE: 84b4dbfffe0bcb6d in the Router Neighbours 0000 with Nwkid: 0ba8 (old Nwkid was 0ba8)'
`

**Comment by pipiche38** [comment]
The device is supported out of the box.
Why you cannot pair, I have no idea.
Please use the Domoticz forum for that
