### ISSUE TITLE
[Model Certification] -  Tuya Smart Zigbee Rain Sensor With Light Detector (TS0207-waterleak)

### ISSUE THREAD

**Issue by j-b-n** [zigbeefordomoticz/z4d-certified-devices#72]
**Tuya Smart Zigbee Rain Sensor With Light Detector** Solar Operated IP66 Outdoor Waterproof Rain Detector 
* TS0207-waterleak
* AliExpress: https://www.aliexpress.com/item/1005007438475434.html?spm=a2g0o.order_list.order_list_main.5.43b41802MssGj4
* Review: https://smarthomescene.com/reviews/tuya-zigbee-solar-rain-sensor-rb-srain01-review/
* There should be more sensors discovered. From what I understand at least 5, from https://github.com/zigpy/zha-device-handlers/issues/3249
* Domoticz forum thread: https://www.domoticz.com/forum/viewtopic.php?p=319899

[export.json](https://github.com/user-attachments/files/16933797/export.json)

**Comment by waltervl** [comment]
I just wanted to make an issue for this device too :-)
I made an export with tuya debug already switched on:
[errors_rainsensor.json.txt](https://github.com/user-attachments/files/16934164/errors_rainsensor.json.txt)

So it would be nice if instead of a Waterleak switch it would be a switch with name 'Droplet Detection (Raining)' 
Also for the other devices a custom sensor would be created with value mV (there is no default mV device in Domoticz)
('illuminance', ea.STATE).withUnit('mV').withDescription('Illuminance level'),
('illuminance_average_20min', ea.STATE).withUnit('mV').withDescription('Illuminance average for the last 20 minutes'),
('illuminance_maximum_today', ea.STATE).withUnit('mV').withDescription('Illuminance maximum for the last 24 hours'),
('rain_intensity', ea.STATE).withUnit('mV').withDescription('Rainfall intensity')

And a switch for 
('cleaning_reminder', ea.STATE, 'ON', 'OFF').withDescription('Cleaning reminder'),

**Comment by pipiche38** [comment]
here is what I suggest:

Lux to monitor the current illuminance
WaterLeak to inform about Rain or not (you can edit and change the image for exemple)
RainingIntensity - will give you the raining intensity in mV
SwitchCleaning - will inform if you need to clean

**Comment by pipiche38** [comment]
This will be available at a point of time on the `wip-stable7-7.1.13` branch

```
git checkout wip-stable7-7.1.13
git pull
sudo python3 -m pip install -r requirements.txt --upgrade
```

**Comment by waltervl** [comment]
Perhaps I was a little bit to early but wip-stable7-7.1.13 gave errors and plugin was not working, see below. Reverting back to stable7 made it working again (git checkout stable7)

2024-09-10 18:20:28.091 Status: ZiGate: Z4D starting with stable7-7.1.012
2024-09-10 18:20:28.098 Status: ZiGate: Z4D loads ZCL Cluster definitions
2024-09-10 18:20:28.127 Status: ZiGate: Z4D loaded 16 configuration from legacy database.
2024-09-10 18:20:28.130 Status: ZiGate: Z4D loads 17 configuration from the local certified Db.
2024-09-10 18:20:28.317 Status: ZiGate: Z4D loads 586 Certified devices from repository.
2024-09-10 18:20:28.318 Status: ZiGate: Z4D loading database
2024-09-10 18:20:28.563 Status: ZiGate: Z4D loads 39 entries from /home/udoox86/domoticz/plugins/Domoticz-Zigate/Data/DeviceList-8.txt
2024-09-10 18:20:28.609 Status: ZiGate: Z4D configured to use transport mode: ZigpyZNP
2024-09-10 18:20:29.913 Error: ZiGate: Call to function 'onStart' failed, exception details:
2024-09-10 18:20:29.916 Error: ZiGate: Traceback (most recent call last):
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1539, in onStart
2024-09-10 18:20:29.916 Error: ZiGate: _plugin.onStart()
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/plugin.py", line 558, in onStart
2024-09-10 18:20:29.916 Error: ZiGate: start_zigbee_transport(self )
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/plugin.py", line 992, in start_zigbee_transport
2024-09-10 18:20:29.916 Error: ZiGate: _start_zigpy_ZNP(self)
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/plugin.py", line 1062, in _start_zigpy_ZNP
2024-09-10 18:20:29.916 Error: ZiGate: from Classes.ZigpyTransport.Transport import ZigpyTransport
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/Classes/ZigpyTransport/Transport.py", line 18, in <module>
2024-09-10 18:20:29.916 Error: ZiGate: from Classes.ZigpyTransport.zigpyThread import (start_zigpy_thread,
2024-09-10 18:20:29.916 Error: ZiGate: File "/home/udoox86/domoticz/plugins/Domoticz-Zigate/Classes/ZigpyTransport/zigpyThread.py", line 779, in <module>
2024-09-10 18:20:29.916 Error: ZiGate: async def zigpy_request( self, device: zigpy.device.Device, profile: t.uint16_t, cluster: t.uint16_t, src_ep: t.uint8_t, dst_ep: t.uint8_t, sequence: t.uint8_t, data: bytes, *, ack_is_disable: bool = True, use_ieee: bool = False, extended_timeout: bool = False, ) -> tuple[zigpy.zcl.foundation.Status, str]:
2024-09-10 18:20:29.916 Error: ZiGate: TypeError: 'type' object is not subscriptable

**Comment by pipiche38** [comment]
@waltervl not sure where this error is coming from. Is the plugin not starting at all ? can you share the full plugin log ?

**Comment by pipiche38** [comment]
Thanks @waltervl for testing it.
Few comments:
- as mentioned here https://github.com/zigbeefordomoticz/z4d-certified-devices/issues/72#issuecomment-2340525604 I'm not expecting to create 20min average, and Max widgets, but yes the rain intensity mV sensor and the cleaning switch should be created.

When I look the export you provided, I expect to have Lux/Water/RainIntensity/SwitchCleaning widgets created. 
Is there any error in the logs (plugin, domoticz ) ? Can you enable debug "Pairing" and "WidgetCreation"  and redo then pairing ?

**Comment by waltervl** [comment]
I will test this evening with pairing logging. The 20 minute avarage lux would be very usefull to steer something on sunshine. So your blinds will not retract on 1 small cloud.... Also rain intensity would be helpfull to have to help identify how heavy it rains.

**Comment by pipiche38** [comment]
@waltervl when doing your test, make sure to get the latest of the wip-stable7-7.1.13 and do an update of the Certified Db to run 5.311

**Comment by waltervl** [comment]
I tried again with pairing and widget debug on (result still the same, only 2 devices created).
[PluginZigbee_pairing.log](https://github.com/user-attachments/files/16966920/PluginZigbee_pairing.log)

I also again tried to update to wip-stable7-7.1.13. The update (git checkout and requirements upgrade) goes fine, no errors.
But after restarting the system Z4D will not start (cannot connect to the coordinator). see the log
[Error_Z4D_wip-stable7-7.1.13.log](https://github.com/user-attachments/files/16966945/Error_Z4D_wip-stable7-7.1.13.log)

When reverting back to stable7 it goes fine again (see the pairing log).

**Comment by waltervl** [comment]
> @waltervl when doing your test, make sure to get the latest of the wip-stable7-7.1.13 and do an update of the Certified Db to run 5.311
log with db 5.311 (but on stable7), still only 2 devices.
[PluginZigbee_pairing_db5311.log](https://github.com/user-attachments/files/16967211/PluginZigbee_pairing_db5311.log)

**Comment by pipiche38** [comment]
I have the impression that you are running python3.8 with Domoticz

> Python Version: 3.8.10 (default, May 26 2023, 14:05:08) \n[GCC 9.4.0]

Can you confirm ? I guess you have an error message in Domoticz log.

**Comment by waltervl** [comment]
Yes running Python Version: 3.8.10 (default, May 26 2023, 14:05:08).

What kind of error message you would have expected about Python and Z4D? I don't see it.

**Comment by waltervl** [comment]
@j-b-n Good that it is working for you. On what python version are you on?

**Comment by j-b-n** [comment]
@waltervl I am running Python 3.9.2.

**Comment by waltervl** [comment]
@pipiche38 On what python version is Z4D supported? Should I upgrade my system? I am currently on Ubuntu 20.4.6LTS

**Comment by pipiche38** [comment]
python3.8 is end of support , so in all cases I encourage you to move to something more recent.
I had a look to the code and for now, the plugin is checking that you are running >= 3.8 so it should be fine.
I don't know what is wrong on your side, and why not all widgets are created. and then you have some issue at startup.

Are you using ZNP or EZSP as the Zigbee coordinator ?

**Comment by waltervl** [comment]
I am using ZNP as zigbee coördinator. I will try some more. Perhaps reboot after going to wip.

**Comment by j-b-n** [comment]
I hope you get it to work Walter. I am experiencing connection loss for some reason. I need to think about why (first I blamed the battery but the sensor seems to wake up when I either trigger "rain" or simply repair it). 

Perhaps time to replace my Conbee II with a ZBDongle-E...

**Comment by waltervl** [comment]
I did not get  wip-stable7-7.1.13 to work yet (did also not try hard yet). But I also see that the device disconnects frequently. It is currently very close to the coordinator and disconnects within a couple of days. I read it also somewhere else that it is not a very stable device.

**Comment by waltervl** [comment]
Updates my system to Ubuntu 24 LTS running python 3.10.
Everything runs fine now. Devices for this rainsensor are being created correctly.

I noticed that the rain sensor has to be close to the coordinator to be running correctly. When connected to a router it disconnect after 24 hours so not really usable.

**Comment by j-b-n** [comment]
True, it seems unstable but from the plug-in perspective the sensor works.

**Comment by pipiche38** [comment]
Sound a good news . @waltervl  are you good if we close that issue ?

**Comment by waltervl** [comment]
Yes, issue can be closed. Thanks!
