### ISSUE TITLE
[Model Certification] - door sensor Tuya TS0601

### ISSUE THREAD

**Issue by domoticauser** [zigbeefordomoticz/z4d-certified-devices#74]
Tuya door sensor TS0601
https://nl.aliexpress.com/item/1005006166715851.html?spm=a2g0o.order_list.order_list_main.115.4d0579d2mJh7t8&gatewayAdapt=glo2nld

Open / Close working
battery level is 200% , that is not okay.
Lux seems to work.
Volt, no idea for what?

[export(2).json](https://github.com/user-attachments/files/17213453/export.2.json)

**Comment by pipiche38** [comment]
kindly test with Certified Db 5.317

**Comment by marktn** [comment]
Hello,

After restart of the [errors.json](https://github.com/user-attachments/files/17438952/errors.json)
 2024-10-18 19:33:55.167 Error: Zigate: This device is not correctly configured, please contact us with the here after information
2024-10-18 19:33:55.179 Error: Zigate: - Device c261
2024-10-18 19:33:55.198 Error: Zigate: - Model TS0601
2024-10-18 19:33:55.207 Error: Zigate: - Manufacturer _TZE200_pay2byax
2024-10-18 19:36:33.950 Error: Zigate: This device is not correctly configured, please contact us with the here after information
2024-10-18 19:36:33.974 Error: Zigate: - Device c261
2024-10-18 19:36:33.999 Error: Zigate: - Model TS0601
2024-10-18 19:36:34.013 Error: Zigate: - Manufacturer _TZE200_pay2byax

**Comment by marktn** [comment]
Extra information.

24-10-18 20:37:24.161 Error: Zigate: Error while receiving a Plugin command: >'NoneType' object has no attribute 'get'<
2024-10-18 20:37:24.167 Error: Zigate: Issue in request {'cmd': 'GET-TIME', 'datas': None, 'NwkId': None, 'TimeStamp': 1729276644.0923717, 'ACKIsDisable': False, 'Sqn': None}, dumping stack: Traceback (most recent call last):
2024-10-18 20:37:24.167 File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 390, in process_incoming_command
2024-10-18 20:37:24.167 await dispatch_command(self, data)
2024-10-18 20:37:24.167 File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Classes/ZigpyTransport/zigpyThread.py", line 421, in dispatch_command
2024-10-18 20:37:24.167 delayAfterSent = datas.get("delayAfterSent", False)
2024-10-18 20:37:24.167 AttributeError: 'NoneType' object has no attribute 'get'
2024-10-18 20:37:24.167

**Comment by pipiche38** [comment]
you need to update the plugin to get at least running [5.317] or greater and then redo the pairing from scratch

**Comment by marktn** [comment]
Thank, looks like it works. Should i do anything whit these notification during update?

`Upgrade the plugin to the most up to date version in the branch you are.
If the upgrade goes well, you will be asked to restart the plugin, otherwise you'll have to do the upgrade manually.
Starting Zigbee for Domoticz plugin Upgrade process.
----------------------------------------------------
PWD=/home/pi/domoticz/plugins/Domoticz-Zigbee
HOME=/home/pi/domoticz/plugins/Domoticz-Zigbee
LANG=nl_NL.UTF-8
INVOCATION_ID=d7cafd320b5d4bcf9025e67d09d90f99
SHLVL=1
JOURNAL_STREAM=8:13279
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
_=/bin/env

UID=0(root) GID=0(root) groepen=0(root)

root

PIP Options: --no-input install -r requirements.txt --ignore-requires-python --upgrade
Current version : {"branch": "stable7", "version": "7.1.012"}
fatal: detected dubious ownership in repository at '/home/pi/domoticz/plugins/Domoticz-Zigbee'
To add an exception for this directory, call:

git config --global --add safe.directory /home/pi/domoticz/plugins/Domoticz-Zigbee
latest git commit:

(1) git config --global --add safe.directory

(2) updating Zigbee for Domoticz plugin

Setup submodule.recurse

hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint: git config pull.rebase false # merge (the default strategy)
hint: git config pull.rebase true # rebase
hint: git config pull.ff only # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
Already up to date.

(3) update python3 modules if needed

WARNING: The directory '/home/pi/domoticz/plugins/Domoticz-Zigbee/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: zigpy in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 2)) (0.69.0)
Collecting zigpy
Downloading zigpy-0.69.0-py3-none-any.whl (218 kB)
Requirement already satisfied: zigpy-cli in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 3)) (1.0.5)
Collecting zigpy-cli
Downloading zigpy_cli-1.0.5-py3-none-any.whl (27 kB)
Downloading zigpy_cli-1.0.4-py3-none-any.whl (27 kB)
Requirement already satisfied: dnspython in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 4)) (2.6.1)
Collecting dnspython
Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
Requirement already satisfied: z4d-certified-devices in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 5)) (5.320)
Collecting z4d-certified-devices
Downloading z4d_certified_devices-5.320-py3-none-any.whl (406 kB)
Downloading z4d_certified_devices-5.319-py3-none-any.whl (406 kB)
Requirement already satisfied: distro in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 6)) (1.9.0)
Collecting distro
Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Downloading distro-1.8.0-py3-none-any.whl (20 kB)
Requirement already satisfied: pyserial-asyncio-fast in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 7)) (0.14)
Collecting pyserial-asyncio-fast
Downloading pyserial_asyncio_fast-0.14-py3-none-any.whl (8.6 kB)
Downloading pyserial_asyncio_fast-0.13-py3-none-any.whl (8.5 kB)
Requirement already satisfied: zigpy_znp in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 8)) (0.13.0)
Collecting zigpy_znp
Downloading zigpy_znp-0.13.0-py3-none-any.whl (120 kB)
Requirement already satisfied: zigpy_deconz in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 9)) (0.24.0)
Collecting zigpy_deconz
Downloading zigpy_deconz-0.24.0-py3-none-any.whl (32 kB)
Requirement already satisfied: bellows in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 10)) (0.41.0)
Collecting bellows
Downloading bellows-0.41.0-py3-none-any.whl (140 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 11)) (2.32.3)
Collecting requests
Downloading requests-2.32.3-py3-none-any.whl (64 kB)
Downloading requests-2.32.2-py3-none-any.whl (63 kB)
Requirement already satisfied: voluptuous in /usr/local/lib/python3.9/dist-packages (from bellows->-r requirements.txt (line 10)) (0.13.1)
Requirement already satisfied: async-timeout in /usr/local/lib/python3.9/dist-packages (from bellows->-r requirements.txt (line 10)) (4.0.2)
Requirement already satisfied: click in /usr/local/lib/python3.9/dist-packages (from bellows->-r requirements.txt (line 10)) (8.1.3)
Requirement already satisfied: click-log>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from bellows->-r requirements.txt (line 10)) (0.4.0)
Requirement already satisfied: pure-pcapy3==1.0.1 in /usr/local/lib/python3.9/dist-packages (from bellows->-r requirements.txt (line 10)) (1.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from pure-pcapy3==1.0.1->bellows->-r requirements.txt (line 10)) (67.8.0)
Requirement already satisfied: attrs in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (22.2.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (3.8.4)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (4.17.3)
Requirement already satisfied: frozendict in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (2.4.6)
Requirement already satisfied: aiosqlite>=0.20.0 in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (0.20.0)
Requirement already satisfied: crccheck in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (40.0.2)
Requirement already satisfied: pyserial-asyncio in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (0.6)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.9/dist-packages (from zigpy->-r requirements.txt (line 2)) (4.9.0)
Requirement already satisfied: pyserial in /usr/local/lib/python3.9/dist-packages (from pyserial-asyncio-fast->-r requirements.txt (line 7)) (3.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.9/dist-packages (from requests->-r requirements.txt (line 11)) (2.0.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 11)) (2020.6.20)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 11)) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 11)) (1.26.5)
Requirement already satisfied: zigpy-zigate>=0.11.0 in /usr/local/lib/python3.9/dist-packages (from zigpy-cli->-r requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: zigpy-xbee>=0.18.0 in /usr/local/lib/python3.9/dist-packages (from zigpy-cli->-r requirements.txt (line 3)) (0.18.1)
Requirement already satisfied: scapy in /usr/local/lib/python3.9/dist-packages (from zigpy-cli->-r requirements.txt (line 3)) (2.5.0)
Requirement already satisfied: zigpy-zboss>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from zigpy-cli->-r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: coloredlogs in /usr/local/lib/python3.9/dist-packages (from zigpy-cli->-r requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: gpiozero in /usr/local/lib/python3.9/dist-packages (from zigpy-zigate>=0.11.0->zigpy-cli->-r requirements.txt (line 3)) (1.6.2)
Requirement already satisfied: pyusb>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from zigpy-zigate>=0.11.0->zigpy-cli->-r requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.9/dist-packages (from aiohttp->zigpy->-r requirements.txt (line 2)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.9/dist-packages (from aiohttp->zigpy->-r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.9/dist-packages (from aiohttp->zigpy->-r requirements.txt (line 2)) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.9/dist-packages (from aiohttp->zigpy->-r requirements.txt (line 2)) (1.8.2)
Requirement already satisfied: humanfriendly>=9.1 in /usr/local/lib/python3.9/dist-packages (from coloredlogs->zigpy-cli->-r requirements.txt (line 3)) (10.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.9/dist-packages (from cryptography->zigpy->-r requirements.txt (line 2)) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.12->cryptography->zigpy->-r requirements.txt (line 2)) (2.21)
Requirement already satisfied: colorzero in /usr/local/lib/python3.9/dist-packages (from gpiozero->zigpy-zigate>=0.11.0->zigpy-cli->-r requirements.txt (line 3)) (2.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.9/dist-packages (from jsonschema->zigpy->-r requirements.txt (line 2)) (0.19.3)

(4) git config --global --unset safe.directory

Plugin Upgrade process completed without errors.`

**Comment by pipiche38** [comment]
Nothing to do, this is just a log to check that all happen correctly. and at the end end you have "Plugin Upgrade process completed without errors.`"

**Comment by pipiche38** [comment]
The plugin is reporting the value provided by the device. If such device do not provide them, we can ot do much.
