### ISSUE TITLE
[Model Certification] - Hama TRV TS0601 _TZE200_h4cgnbzg

### ISSUE THREAD

**Issue by nixxzn** [zigbeefordomoticz/z4d-certified-devices#76]
Hi, I recently bought the following device without full support yet:
https://www.amazon.de/dp/B08GSRV3PB?ref=ppx_yo2ov_dt_b_fed_asin_title
Name: Hama Smartes Heizkörperthermostat

Please see: https://zigbee.blakadder.com/Hama_00176592.html
Zigbee ID: _TZE200_h4cgnbzg

Domoticz log from first inclusion attempt:
```javascript
2024-10-06 20:47:04.991 Error: Zigate: This device is not correctly configured, please contact us with the here after information
2024-10-06 20:47:05.020 Error: Zigate: - Device 9edc
2024-10-06 20:47:05.150 Error: Zigate: - Model TS0601
2024-10-06 20:47:05.281 Error: Zigate: - Manufacturer _TZE200_h4cgnbzg
``` 

Domoticz version: 2024.7
Plugin version: 7.1.012

As a workaround for me, I have added
"_TZE200_h4cgnbzg",
to the array "TUYA_eTRV3_MANUFACTURER"
in file "../Domoticz-Zigbee/Modules/tuyaConst.py"

Herewith, 3 devices are created on a new inclusion attempt: Temp, SetPoint and Switch.
All are working fine for reading and writing.
Nevertheless, I got some errors on inclusion:

```javascript
2024-10-07 07:43:05.455 Status: Zigate: [None] NEW OBJECT: 5002 None
2024-10-07 07:43:05.860 Status: Zigate: [-] NEW OBJECT: 5002 Active Endpoint Response Ep: 01 LQI: 60
2024-10-07 07:43:05.864 Status: Zigate: [-] NEW OBJECT: 5002 Request Simple Descriptor for Ep: 01
2024-10-07 07:43:05.982 Status: Zigate: [-] NEW OBJECT: 5002 Simple Descriptor Response EP: 0x01 LQI: 60
2024-10-07 07:43:05.985 Status: Zigate: [-] NEW OBJECT: 5002 ProfileID 0104
2024-10-07 07:43:05.987 Status: Zigate: [-] NEW OBJECT: 5002 ZDeviceID 0051
2024-10-07 07:43:05.990 Status: Zigate: [-] NEW OBJECT: 5002 Application Version 0001
2024-10-07 07:43:05.992 Status: Zigate: [-] NEW OBJECT: 5002 Cluster IN Count: 04
2024-10-07 07:43:05.994 Status: Zigate: [-] NEW OBJECT: 5002 Cluster In 1: 0004 (Groups)
2024-10-07 07:43:05.996 Status: Zigate: [-] NEW OBJECT: 5002 Cluster In 2: 0005 (Scenes)
2024-10-07 07:43:05.998 Status: Zigate: [-] NEW OBJECT: 5002 Cluster In 3: ef00
2024-10-07 07:43:06.000 Status: Zigate: [-] NEW OBJECT: 5002 Cluster In 4: 0000 (Basic)
2024-10-07 07:43:06.002 Status: Zigate: [-] NEW OBJECT: 5002 Cluster OUT Count: 02
2024-10-07 07:43:06.004 Status: Zigate: [-] NEW OBJECT: 5002 Cluster Out 1: 0019 (Over-the-Air Upgrade)
2024-10-07 07:43:06.006 Status: Zigate: [-] NEW OBJECT: 5002 Cluster Out 2: 000a (Time)
2024-10-07 07:43:07.107 Status: Zigate: [0] NEW OBJECT: 5002 Model Name: TS0601-eTRV3
2024-10-07 07:43:07.116 Status: Zigate: [0] NEW OBJECT: 5002 Manufacturer Name: _TZE200_h4cgnbzg
2024-10-07 07:43:07.124 Status: Zigate: [None] NEW OBJECT: 5002 Request Node Descriptor
2024-10-07 07:43:07.195 Error: Zigate: Call to function 'onHeartbeat' failed, exception details:
2024-10-07 07:43:07.280 Error: Zigate: Traceback (most recent call last):
2024-10-07 07:43:07.281 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/plugin.py", line 1573, in onHeartbeat
2024-10-07 07:43:07.281 Error: Zigate: _plugin.onHeartbeat()
2024-10-07 07:43:07.281 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/plugin.py", line 886, in onHeartbeat
2024-10-07 07:43:07.281 Error: Zigate: processListOfDevices(self, Devices)
2024-10-07 07:43:07.282 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/heartbeat.py", line 1000, in processListOfDevices
2024-10-07 07:43:07.282 Error: Zigate: processNotinDBDevices(self, Devices, NwkId, status, RIA)
2024-10-07 07:43:07.282 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/pairingProcess.py", line 126, in processNotinDBDevices
2024-10-07 07:43:07.283 Error: Zigate: interview_state_createDB(self, Devices, NWKID, RIA, status)
2024-10-07 07:43:07.283 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/pairingProcess.py", line 348, in interview_state_createDB
2024-10-07 07:43:07.283 Error: Zigate: full_provision_device(self, Devices, NWKID, RIA, status)
2024-10-07 07:43:07.283 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/pairingProcess.py", line 395, in full_provision_device
2024-10-07 07:43:07.284 Error: Zigate: zigbee_provision_device(self, Devices, NWKID, RIA, status)
2024-10-07 07:43:07.284 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/pairingProcess.py", line 457, in zigbee_provision_device
2024-10-07 07:43:07.284 Error: Zigate: handle_device_specific_needs(self, Devices, NWKID)
2024-10-07 07:43:07.284 Error: Zigate: File "/home/pi/domoticz/plugins/Domoticz-Zigbee/Modules/pairingProcess.py", line 656, in handle_device_specific_needs
2024-10-07 07:43:07.285 Error: Zigate: tuya_eTRV_registration(self, NWKID, ty_data_request=True)
2024-10-07 07:43:07.285 Error: Zigate: TypeError: tuya_eTRV_registration() got an unexpected keyword argument 'ty_data_request'
2024-10-07 07:43:08.897 Zigate: Assisted Pairing: Polling: ['5002']
2024-10-07 07:43:08.898 Zigate: --> New device: 5002
2024-10-07 07:43:08.898 Zigate: --> inDB , removed 5002 from List
2024-10-07 07:43:08.900 Zigate: ------> New Cluster: {'ClusterId': '0000', 'ClusterDesc': 'Basic'}
2024-10-07 07:43:08.901 Zigate: ------> New Cluster: {'ClusterId': '0004', 'ClusterDesc': 'Groups'}
2024-10-07 07:43:08.901 Zigate: ------> New Cluster: {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}
2024-10-07 07:43:08.901 Zigate: ------> New Cluster: {'ClusterId': '000a', 'ClusterDesc': 'Time'}
2024-10-07 07:43:08.902 Zigate: ------> New Cluster: {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}
2024-10-07 07:43:08.902 Zigate: ----> New Ep: {'Ep': '01', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0004', 'ClusterDesc': 'Groups'}, {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}, {'ClusterId': '000a', 'ClusterDesc': 'Time'}, {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}]}
2024-10-07 07:43:08.906 Zigate: --> New Device: {'NwkId': '5002', 'ProvisionStatus': 'inDB', 'ProvisionStatusDesc': 'inDB', 'IEEE': 'a4c1385568f3c1cb', 'ProfileId': '0104', 'ProfileIdDesc': 'ZHA', 'ZDeviceID': '0051', 'ZDeviceIDDesc': 'Unknow', 'Model': 'TS0601-eTRV3', 'PluginCertified': 'yes', 'Ep': [{'Ep': '01', 'Clusters': [{'ClusterId': '0000', 'ClusterDesc': 'Basic'}, {'ClusterId': '0004', 'ClusterDesc': 'Groups'}, {'ClusterId': 'ef00', 'ClusterDesc': 'Unknown'}, {'ClusterId': '000a', 'ClusterDesc': 'Time'}, {'ClusterId': '0019', 'ClusterDesc': 'Over-the-Air Upgrade'}]}]}
``` 

[export.json](https://github.com/user-attachments/files/17282993/export.json)

**Comment by pipiche38** [comment]
Kindly update the Certified Db to reach at least 5.315. The device will automatically be recognized as eTRV3

**Comment by nixxzn** [comment]
Updated and looks good! Thanks :-)
